<a href="https://colab.research.google.com/github/Tomytool/pythonClass/blob/main/clase_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vR_O9zKC4dBlTo75Djw9J5VbDE6_Ag_eElctDxORdleXY_7mhZXpOI8cXD46XjlyndIGDXoDEBayVTp/pub?gid=0&single=true&output=csv")
df

actividad  curso 1  curso 2  curso 3  curso 4
0    Actividad 1        5        5        4        4
1    Actividad 2        6        3        6        5
2    Actividad 3        4        3        5        3
3    Actividad 4        3        3        7        6
4    Actividad 5        7        4        4        3
5    Actividad 6        5        5        5        4
6    Actividad 7        4        5        6        5
7    Actividad 8        7        6        3        6
8    Actividad 9        3        4        4        5
9   Actividad 10        5        4        5        4
10  Actividad 11        4        3        3        3
11  Actividad 12        6        5        4        7
12  Actividad 13        3        6        6        3
13  Actividad 14        7        4        7        4
14  Actividad 15        3        7        3        5
15  Actividad 16        7        4        4        2

In [19]:
segunda_columna = df.iloc[:, 1].tolist()
print(segunda_columna)

[5, 6, 4, 3, 7, 5, 4, 7, 3, 5, 4, 6, 3, 7, 3, 7]


In [20]:
promedio = sum(segunda_columna) / len(segunda_columna)
round(promedio, 2)

4.94

# Task
Generate a bar chart showing the average of each column in the dataframe `df`, excluding the 'actividad' column.

## Calculate column averages

### Subtask:
Calculate the average of each column in the dataframe `df`, excluding the 'actividad' column.


**Reasoning**:
Calculate the mean of each numerical column in the DataFrame, excluding the 'actividad' column, and store the results.



In [21]:
column_averages = df.drop(columns=['actividad']).mean()
print(column_averages)

curso 1    4.9375
curso 2    4.4375
curso 3    4.7500
curso 4    4.3125
dtype: float64


## Prepare data for plotting

### Subtask:
Organize the calculated averages into a format suitable for plotting.


**Reasoning**:
Convert the pandas Series of column averages into a DataFrame and format it for plotting by renaming columns.



In [22]:
df_averages = column_averages.reset_index()
df_averages.columns = ['Course', 'Average Score']
display(df_averages)

Course  Average Score
0  curso 1         4.9375
1  curso 2         4.4375
2  curso 3         4.7500
3  curso 4         4.3125

## Generate bar chart

### Subtask:
Create a bar chart to visualize the average of each column.


**Reasoning**:
Generate a bar chart using the prepared DataFrame to visualize the average scores per course.



In [23]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.bar(df_averages['Course'], df_averages['Average Score'])
plt.xlabel('Course')
plt.ylabel('Average Score')
plt.title('Average Scores per Course')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

## Summary:

### Data Analysis Key Findings

*   The average scores for the courses are: 'curso 1' (4.94), 'curso 2' (4.44), 'curso 3' (4.75), and 'curso 4' (4.31).
*   'curso 1' has the highest average score among the courses analyzed.
*   'curso 4' has the lowest average score among the courses analyzed.

### Insights or Next Steps

*   Investigate potential reasons for the lower average scores in 'curso 2' and 'curso 4' compared to 'curso 1' and 'curso 3'.
